# here we'll tell ansible when you wanna connect to backend group jump using bastion ip 
#variables that should apply to the backend group machines 

ansible_user: ubuntu

ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o UserKnownHostsFile=/dev/null
  -o ProxyCommand="ssh -W %h:%p -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -q ubuntu@{{ hostvars[groups['bastion'] | intersect(groups[env_name]) | first]['ansible_host'] }}"
#-o ProxyJump=ubuntu@{{ hostvars[groups['bastion'] | 
# intersect(groups[env_name]) | first]['ansible_host'] }}
#the first line : disabled the prompt : are you sure you want to connect ...
#second line : First SSH into this jump host, then from there reach the destination.
#third line : chose the first rignt bastion that exist in bastion group and env_name group 
#ansible_host is a parameter of hostvars 
#hostvars : It is a built-in Ansible variable that Ansible automatically builds when it reads your inventory. It contains every host and every variable Ansible knows about for each host.
#this is jinja 2 syntaxe
#means for the group backend because we use separate : "" find the hosts [0] take the first one and we have only one 
#[0]makes a huge conflict when running the environment because the second environment always uses the first host 
#which makes the second env uses the bastion of the first env so it'll connect to the wrong database and backend 
#the public ip of bastion server : 35.84.32.227