#this is where we'll run combinations 
#will define the hosts with the roles to be used 

- hosts : nginx #ansible has already the variables for the nginx host discovered by compose in the dynamic inventoy 
  become : true #and ansible uses those vaiables to connect over ssh 
  roles :
    - common
    - nginx   #it can uses the first tf workspace nginx 

- hosts : backend  #it can uses the first workspace backend because ansible just discover ips via roles  
  become : true
  roles :
    - common
    - backend

- hosts : database 
  become : true
  roles :
    - common
    - database      

  