#variables that should apply to the backend group machines

ansible_user: ubuntu

ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o ProxyJump=ubuntu@{{ hostvars[groups['bastion'] | 
  intersect(groups[env_name]) | first]['ansible_host'] }}

#no need for ssh agent