#role for the database whatever the input value : PostgreSql or MySql or MongoDB 
# I need to load the variables of the database chosen using include_vars 
#firewalls :ingres: 5432/tcp , 3306/tcp , 27017/tcp ,no egress need to be fixed 

- name : deny any incoming traffic by default 
  community.general.ufw :
    direction : incoming
    default : deny 

- name : allow outgoing by default 
  community.general.ufw :
    direction : outgoing
    default : allow 

- name: allow all trafic comming from port 5432/tcp , 3306/tcp , 27017/tcp , from backend_sg 
  community.general.ufw :
    rule: allow
    port : >-
               {%- if db_engine == "postgres" -%}
               5432
               {%- elif db_engine == "mysql" -%}
               3306
               {%- else -%}
               27017 
               {%- endif -%}
    proto : tcp
    src : "{{ hostvars[groups['backend'] | intersect(groups[env_name]) | first]['ansible_host'] }}"
    direction : in 
    
- name: allow ssh traffic comming from the bastion
  community.general.ufw :
    rule: allow
    port : '22'
    proto : tcp
    src : "{{ hostvars[groups['bastion'] | intersect(groups[env_name]) | first]['ansible_host'] }}"
    direction : in

- name: enable UFW
  community.general.ufw:
    state: enabled

#- name: load variables
 # ansible.builtin.include_vars:
  #  file: "{{ playbook_dir }}/vars/{{db_engine}}.yaml"

- name: Load database secret
  ansible.builtin.set_fact:
    database_secrets: "{{lookup('amazon.aws.secretsmanager_secret',db_engine, region='us-east-1') | from_json }}"

- name: demarrer container
  community.docker.docker_container:
    name: "{{ db_engine }}"
    image: >-
             {%- if db_engine == "postgres" -%}
                postgres:latest
             {%- elif db_engine == "mysql" -%}
                mysql:latest
             {%- else -%}
                mongo:7.0
             {%- endif -%}
    state: started 
    published_ports:
      - >- #host port (EC2) : container port 
          {%- if db_engine == "postgres" -%}
          5432:5432
          {%- elif db_engine == "mysql" -%}
          3306:3306
          {%- else -%}
          27017:27017 
          {%- endif -%}
    env: "{{ database_secrets.db_env_vars }}"
