server {
    listen 80;
    
    location / {
        proxy_pass http://10.0.2.10:5000;
    }
    location /health {
        proxy_pass http://10.0.2.10:5000/health;
    }
    location /api/info {
        proxy_pass http://10.0.2.10:5000/api/info;
    }

}
#in case I wanna allow also https but I will need security certificates I'll need it in the secueity phase 
#server {
    #listen 443 ssl;
    #certifications 
    #ssl_certificate /currentpath/cert.pem
    #ssl_certificate_key /currentpathkey.pem 
    #location / {
        #proxy_pass http://10.0.2.10:5000;
    #}
    #location /health {
        #proxy_pass http://10.0.2.10:5000/health;
    #}
    #location /api/info {
        #proxy_pass http://10.0.2.10:5000/api/info;
    #}
#}