# each play is for a tier in this app we have only the backend so we use one play
- name: pull the image and run the application on aws 
  # - dashes means the order of the list that Ansible will proceede
  hosts: backend
  #remote_user: root
  become: true 
  #gather_facts :yes , make ansible know about the state of my host 
    
  tasks:
    #is a module = small specific task 
    - name: installer docker
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: true

    - name: demaarrer docker 
      ansible.builtin.service:
        name: docker
        enabled: true
        state: started 

    - name: Install Docker SDK for Python
      ansible.builtin.apt:
        name: python3-docker
        state: present
        
    - name: pull the image from docker hub
      community.docker.docker_image_pull:
        name: mohammedbentimzal/bentimzalhub:v1

    - name: demarrer container
      community.docker.docker_container:
        name: flask_app_container
        image: mohammedbentimzal/bentimzalhub:v1
        state: started 
        published_ports:
          - "5000:5000" 



    #modules prewritten tool that cando the job for me 
      #par ametersinstructions to what to do
    #keywords , become : true : run this task as a root 
    #when ansible_facts.services['nginx.service'].state = 'running'
    #connection: local , connection: ssh , 
    



  
